export type LangMode = 'ar' | 'en';

export function getMarketingContent(language: string) {
  const lang: LangMode = language === 'ar' ? 'ar' : 'en';

  return lang === 'ar'
    ? {
        brand: 'Bookati',
        heroBadge: 'من الأول للمشاريع والأعمال السعودية',
        heroTitle: 'كل اللي تحتاجه تضبّط شغلك من مكان واحد',
        heroSubtitle:
          'نظام حجوزات وتشغيل وتجربة عملاء مترابطة: يزوّدك حجوزات أكثر، يخلّي فريقك مرتب، ويرفع ربحك من غير تعقيد ولا لفّ ودوران.',
        ctaPrimary: 'ابدأ التجربة المجانية',
        ctaSecondary: 'احجز عرضًا تجريبيًا',
        trust: ['بدون ما تحط بطاقة', 'تجربة مجانية 30 يوم', 'إلغاء متى ما حابّ'],
        stats: [
          { value: '40%', label: 'زيادة بالحجوزات' },
          { value: '60%', label: 'توفير بوقت الشغل' },
          { value: '95%', label: 'رضا العملاء' },
          { value: '24/7', label: 'حجز أونلاين على طول' },
        ],
        overviewTitle: 'شوف إيش يقدّم لك النظام',
        overviewSubtitle:
          'مزايا واضحة وبسيطة، حتى اللي مو من أهل التقنية يفهمها ويقدر يشتغل عليها من أول يوم.',
        overviewFeatures: [
          {
            key: 'dashboard',
            title: 'لوحة تحكم تضبطها على كيفك',
            desc: 'رتّب الويدجت بالسحب والإفلات حسب أولوياتك.',
            benefit: 'تشوف أهم الأرقام باللمحة.',
          },
          {
            key: 'multilang',
            title: 'عربي أولًا، ولغات ثانية إذا احتجت',
            desc: 'واجهة عربية من اليمين لليسار، مع دعم لغات إضافية للفريق.',
            benefit: 'سهل على كل أعضاء فريقك.',
          },
          {
            key: 'roles',
            title: 'صلاحيات على كيف كل موظّف',
            desc: 'مدير، موظّف، أو صلاحيات مخصّصة حسب شغلك.',
            benefit: 'تحكم واضح: مين يشوف إيش ويعدّل إيش.',
          },
          {
            key: 'branches',
            title: 'فروعك كلها تحت حساب واحد',
            desc: 'تشغيل كل فرع من نفس النظام بدون فوضى.',
            benefit: 'توحيد الإجراءات وتقليل الغلطات.',
          },
          {
            key: 'bookings',
            title: 'حجوزات متقدّمة بس مو معقّدة',
            desc: 'حجز، تعديل، تأكيد، وتحديثات لحظية.',
            benefit: 'تشغيل أسرع وتجربة أحلى لعملاءك.',
          },
          {
            key: 'tags',
            title: 'تسعير بالوسوم يوافق نوع الخدمة',
            desc: 'اضبط المدة والرسوم حسب نوع الطلب.',
            benefit: 'تسعير أدق وربح أوضح.',
          },
          {
            key: 'analytics',
            title: 'تقارير وتحليلات تفيد قرارك',
            desc: 'متابعة الحجوزات، الزيارات، والمعاملات.',
            benefit: 'قرارات مبنية على أرقام حقيقية مو تخمين.',
          },
          {
            key: 'integrations',
            title: 'تكاملات جاهزة مع أنظمة الشغل',
            desc: 'تكامل مع Zoho وDaftra، وجاهزين نوسّع لاحقًا.',
            benefit: 'شغلك مترابط من غير تكرار يدوي.',
          },
        ],
        coreGridTitle: 'أساسيات تشغيل نشاطك',
        coreGridSubtitle: 'كل كرت يمثّل جزء مهم من دورة الخدمة والبيع.',
        coreCards: [
          { key: 'booking', title: 'نظام الحجوزات', desc: 'إدارة الحجوزات من اللوحة، ورابط حجز للعملاء برّه.' },
          { key: 'landing', title: 'صفحة الحجز والموقع', desc: 'محرّر للصفحة العامة ورابط حجز باسم نشاطك.' },
          { key: 'pos', title: 'الاستقبال والكاشير', desc: 'استقبال للزيارة والبيع، وكاشير للسداد والمعاملات.' },
          { key: 'packages', title: 'الباقات والمشتركين', desc: 'باقات، اشتراكات، ومتابعة المشتركين بسهولة.' },
          { key: 'offers', title: 'العروض والترويج', desc: 'عروض وخصومات ترفع الحركة والمبيعات.' },
          { key: 'branches', title: 'إدارة الفروع', desc: 'أكثر من فرع على نفس الحساب.' },
          { key: 'tags', title: 'الخدمات والوسوم', desc: 'كتالوج خدمات وتسعير مرن بالوسوم والمدة.' },
          { key: 'employees', title: 'الموظفين والورديات', desc: 'فريق العمل، الورديات، والتعيين حسب طريقة شغلك.' },
          { key: 'reports', title: 'التقارير والتصدير', desc: 'زيارات، حجوزات، معاملات، وCSV / Excel / PDF.' },
          { key: 'customers', title: 'بوابة العميل', desc: 'دخول العميل، لوحته، وحسابه وفواتيره.' },
          { key: 'roles', title: 'الأدوار واللوحة', desc: 'صلاحيات مخصّصة وتخصيص اللوحة بالويدجت.' },
        ],
        advantagesTitle: 'ليش بوكاتي يفرق معك؟',
        advantagesSubtitle: 'مزايا عملية تناسب طبيعة السوق السعودي وتشغيل المحل والفروع.',
        sellTitle: 'إيش تقدر تبيعه من نظام واحد؟',
        sellSubtitle: 'حوّل كل نموذج بيع إلى تدفّق تشغيل واضح ومربح.',
        industriesTitle: 'حلول حسب نوع نشاطك',
        industriesSubtitle: 'صفحات مخصّصة لكل قطاع مع أمثلة شغل حقيقية.',
        partnersTitle: 'شركاؤنا وتكاملاتنا',
        partnersSubtitle: 'تكاملات جاهزة الحين، وبنية تسمح لك تكبّر لاحقًا.',
        dashboardPowerTitle: 'قوّة النظام في لوحة وحدة',
        dashboardPowerSubtitle: 'ويدجت تضبطها على كيفك، أرقام لحظية، ورؤية تنفيذية واضحة.',
        rolesTitle: 'صلاحيات تضبط مين يشتغل وإيش',
        rolesSubtitle: 'افصل شغل الإدارة عن التشغيل اليومي بدقّة.',
        reportsTitle: 'تقارير تخلّيك تقرّر أسرع',
        reportsSubtitle: 'متابعة الزيارات، الحجوزات، والمعاملات مع تصدير بعدة صيغ.',
        mobileTitle: 'تجربة جوّال عملية للفريق',
        mobileSubtitle: 'تحديثات لحظية للحجوزات وتنبيهات توصّل الموظّف على طول.',
        faqTitle: 'الأسئلة الشائعة',
        faqSubtitle: 'إجابات سريعة قبل ما تبدأ.',
        faqItems: [
          { q: 'هل أحتاج بطاقة للتجربة؟', a: 'لا، تقدر تبدأ التجربة المجانية من غير ما تحط بطاقة.' },
          { q: 'هل يدعم أكثر من فرع؟', a: 'إيه، تقدر تدير كل فروعك من نفس الحساب.' },
          { q: 'هل أقدر أحدد صلاحيات مختلفة للموظفين؟', a: 'أكيد، عندك أدوار وصلاحيات مخصّصة لكل واحد حسب شغله.' },
          { q: 'هل أقدر أبيع خدمات ومنتجات واشتراكات معًا؟', a: 'نعم، تدير أنواع البيع المختلفة من نفس المنصة.' },
          { q: 'هل التقارير تنصدر؟', a: 'إيه، التصدير متاح بصيغ CSV وExcel وPDF.' },
          { q: 'في تكامل مع Zoho وDaftra؟', a: 'نعم، التكاملات جاهزة ضمن النظام.' },
        ],
        finalTitle: 'جاهز ترفع مستوى تشغيل نشاطك؟',
        finalSubtitle: 'ابدأ الحين وجرّب الإمكانيات بنفسك.',
        learnAdvantages: 'شوف كل المزايا',
        exploreIndustries: 'تصفّح القطاعات',
      }
    : {
        brand: 'Bookati',
        heroBadge: 'Built For Saudi Businesses',
        heroTitle: 'Run your entire business from one smart platform',
        heroSubtitle:
          'A complete operating system for bookings, sales, team workflows, and customer experience.',
        ctaPrimary: 'Start Free Trial',
        ctaSecondary: 'Book Demo',
        trust: ['No credit card required', '30-day free trial', 'Cancel anytime'],
        stats: [
          { value: '40%', label: 'More bookings' },
          { value: '60%', label: 'Time saved' },
          { value: '95%', label: 'Customer satisfaction' },
          { value: '24/7', label: 'Online booking' },
        ],
        overviewTitle: 'Everything you need to know',
        overviewSubtitle: 'Clear and simple capabilities for non-technical teams.',
        overviewFeatures: [
          { key: 'dashboard', title: 'Custom Dashboard', desc: 'Drag-and-drop widgets based on your priorities.', benefit: 'See key KPIs instantly.' },
          { key: 'multilang', title: 'Multi-language system', desc: 'Arabic RTL-first UI with additional language support.', benefit: 'Easy adoption for diverse teams.' },
          { key: 'roles', title: 'Role-based permissions', desc: 'Admin, Employee, and custom role structures.', benefit: 'Precise control over access.' },
          { key: 'branches', title: 'Branch management', desc: 'Manage all branches from one platform.', benefit: 'Consistent operations across locations.' },
          { key: 'bookings', title: 'Advanced booking flow', desc: 'Create, edit, confirm, and track bookings in one flow.', benefit: 'Faster execution and better CX.' },
          { key: 'tags', title: 'Tag-based pricing', desc: 'Control slot duration and fee behavior by service context.', benefit: 'More accurate pricing logic.' },
          { key: 'analytics', title: 'Reports & analytics', desc: 'Track bookings, visitors, and transactions.', benefit: 'Decisions backed by real data.' },
          { key: 'integrations', title: 'Business integrations', desc: 'Zoho and Daftra with future-ready extension model.', benefit: 'Connected workflows, less manual effort.' },
        ],
        coreGridTitle: 'Core modules in one place',
        coreGridSubtitle: 'Each card represents a key business capability.',
        coreCards: [
          { key: 'booking', title: 'Bookings', desc: 'Admin booking management plus the public booking flow.' },
          { key: 'landing', title: 'Landing & booking link', desc: 'Public landing editor and your branded booking URL.' },
          { key: 'pos', title: 'Reception & cashier', desc: 'Reception for visits and sales; cashier checkout flows.' },
          { key: 'packages', title: 'Packages & subscribers', desc: 'Plans, renewals, and subscriber management.' },
          { key: 'offers', title: 'Offers & promotions', desc: 'Discounts and campaigns to lift conversions.' },
          { key: 'branches', title: 'Branches', desc: 'Multi-location operations from one account.' },
          { key: 'tags', title: 'Services & pricing tags', desc: 'Service catalog with tag-based duration and pricing.' },
          { key: 'employees', title: 'Staff & shifts', desc: 'Team roster and shift scheduling when enabled.' },
          { key: 'reports', title: 'Reports & exports', desc: 'Visitors, bookings, transactions, CSV/Excel/PDF.' },
          { key: 'customers', title: 'Customer portal', desc: 'Customer login, dashboard, and billing access.' },
          { key: 'roles', title: 'Roles & dashboard', desc: 'Custom permissions and drag-and-drop dashboard widgets.' },
        ],
        advantagesTitle: 'Why we are different',
        advantagesSubtitle: 'Real competitive advantages for Saudi market.',
        sellTitle: 'What you can sell',
        sellSubtitle: 'Service, product, package, subscription, and tickets.',
        industriesTitle: 'Industry-ready solutions',
        industriesSubtitle: 'Tailored use cases for each business type.',
        partnersTitle: 'Partners & Integrations',
        partnersSubtitle: 'Ready integrations now, expandable architecture for future.',
        dashboardPowerTitle: 'Operational power in one dashboard',
        dashboardPowerSubtitle: 'Drag-and-drop widgets and real-time business visibility.',
        rolesTitle: 'Role-based control',
        rolesSubtitle: 'Admin, employee, and custom role permissions.',
        reportsTitle: 'Actionable analytics',
        reportsSubtitle: 'Bookings, visitors, transactions, and exports.',
        mobileTitle: 'Mobile-first team experience',
        mobileSubtitle: 'Instant updates and notifications on the go.',
        faqTitle: 'Frequently asked questions',
        faqSubtitle: 'Quick answers before you start.',
        faqItems: [
          { q: 'Do I need a credit card to start?', a: 'No. You can start the free trial without a credit card.' },
          { q: 'Can I manage multiple branches?', a: 'Yes, multi-branch operations are supported from one account.' },
          { q: 'Can I control staff permissions?', a: 'Yes, you can configure role-based and custom permissions.' },
          { q: 'Can I sell services, products, and subscriptions together?', a: 'Yes, the platform supports multiple selling models in one flow.' },
          { q: 'Can reports be exported?', a: 'Yes, exports are available in CSV, Excel, and PDF.' },
          { q: 'Do you support Zoho and Daftra integrations?', a: 'Yes, both integrations are supported.' },
        ],
        finalTitle: 'Ready to scale your operations?',
        finalSubtitle: 'Start free and see the value yourself.',
        learnAdvantages: 'View all advantages',
        exploreIndustries: 'Explore industries',
      };
}

