export type LangMode = 'ar' | 'en';

export function getMarketingContent(language: string) {
  const lang: LangMode = language === 'ar' ? 'ar' : 'en';

  return lang === 'ar'
    ? {
        brand: 'Bookati',
        heroBadge: 'مبني للأعمال في السعودية',
        heroTitle: 'كل ما تحتاجه لإدارة وتشغيل نشاطك من مكان واحد',
        heroSubtitle:
          'نظام حجوزات وتشغيل وتجربة عميل متكامل يساعدك على زيادة الحجوزات، تنظيم الفريق، ورفع الأرباح بدون تعقيد.',
        ctaPrimary: 'ابدأ التجربة المجانية',
        ctaSecondary: 'احجز عرضًا تجريبيًا',
        trust: ['بدون بطاقة ائتمانية', 'تجربة مجانية 30 يوم', 'إلغاء في أي وقت'],
        stats: [
          { value: '40%', label: 'زيادة في الحجوزات' },
          { value: '60%', label: 'توفير في وقت التشغيل' },
          { value: '95%', label: 'رضا العملاء' },
          { value: '24/7', label: 'حجز أونلاين' },
        ],
        overviewTitle: 'كل ما تحتاج معرفته عن النظام',
        overviewSubtitle: 'مزايا واضحة وسهلة لغير التقنيين، مصممة لتبسيط التشغيل اليومي.',
        overviewFeatures: [
          { key: 'dashboard', title: 'لوحة تحكم قابلة للتخصيص', desc: 'رتب الويدجت بالسحب والإفلات حسب أولوياتك.', benefit: 'تشوف أهم الأرقام بسرعة.' },
          { key: 'multilang', title: 'نظام متعدد اللغات', desc: 'واجهة عربية RTL مع دعم لغات إضافية.', benefit: 'سهولة استخدام لكل فريقك.' },
          { key: 'roles', title: 'صلاحيات مرنة حسب الدور', desc: 'Admin / Employee / صلاحيات مخصصة.', benefit: 'تحكم كامل في من يرى ماذا.' },
          { key: 'branches', title: 'إدارة الفروع', desc: 'إدارة تشغيل كل فرع من نفس النظام.', benefit: 'توحيد الإدارة وتقليل الأخطاء.' },
          { key: 'bookings', title: 'نظام حجوزات متقدم', desc: 'حجز، تعديل، تأكيد، وتحديثات فورية.', benefit: 'تشغيل أسرع وتجربة عميل أفضل.' },
          { key: 'tags', title: 'تسعير بالوسوم', desc: 'تحكم بالمدة والرسوم حسب نوع الطلب.', benefit: 'تسعير أدق وربحية أوضح.' },
          { key: 'analytics', title: 'تقارير وتحليلات', desc: 'متابعة الحجوزات، الزيارات، والمعاملات.', benefit: 'قرارات مبنية على بيانات حقيقية.' },
          { key: 'integrations', title: 'تكاملات الأعمال', desc: 'تكامل مع Zoho وDaftra وجاهز للمزيد.', benefit: 'تشغيل مترابط بدون تكرار عمل.' },
        ],
        coreGridTitle: 'المنظومة الأساسية لنشاطك',
        coreGridSubtitle: 'كل كرت يمثل جزءًا تشغيليًا مهمًا في دورة البيع والخدمة.',
        coreCards: [
          { key: 'booking', title: 'نظام الحجوزات', desc: 'إدارة الحجوزات في لوحة التحكم مع تدفق حجز للعملاء.' },
          { key: 'landing', title: 'صفحة الحجز والموقع', desc: 'محرر الصفحة العامة ورابط حجز باسم النشاط.' },
          { key: 'pos', title: 'الاستقبال والكاشير', desc: 'واجهة استقبال للزيارات والبيع؛ كاشير للمعاملات.' },
          { key: 'packages', title: 'الباقات والمشتركين', desc: 'باقات، اشتراكات، ومتابعة المشتركين.' },
          { key: 'offers', title: 'العروض والترويج', desc: 'عروض وخصومات لتنشيط المبيعات.' },
          { key: 'branches', title: 'إدارة الفروع', desc: 'أكثر من فرع من نفس الحساب.' },
          { key: 'tags', title: 'الخدمات والوسوم', desc: 'كتالوج خدمات وتسعير مرن بالوسوم والمدة.' },
          { key: 'employees', title: 'الموظفين والورديات', desc: 'فريق العمل وورديات وتعيين حسب نموذج التشغيل.' },
          { key: 'reports', title: 'التقارير والتصدير', desc: 'زيارات، حجوزات، معاملات، وCSV / Excel / PDF.' },
          { key: 'customers', title: 'بوابة العميل', desc: 'تسجيل دخول العميل، لوحة، وحساب وفوترة.' },
          { key: 'roles', title: 'الأدوار واللوحة', desc: 'صلاحيات مخصصة وتخصيص لوحة التحكم بالويدجت.' },
        ],
        advantagesTitle: 'لماذا نحن مختلفون؟',
        advantagesSubtitle: 'مزايا تنافسية حقيقية تناسب السوق السعودي.',
        sellTitle: 'ما يمكنك بيعه من نظام واحد',
        sellSubtitle: 'حوّل كل نموذج بيع إلى تدفق تشغيل واضح ومربح.',
        industriesTitle: 'حلول حسب نوع النشاط',
        industriesSubtitle: 'صفحات متخصصة لكل قطاع مع حالات استخدام عملية.',
        partnersTitle: 'شركاؤنا وتكاملاتنا',
        partnersSubtitle: 'تكاملات جاهزة اليوم، وبنية مرنة للتوسّع لاحقًا.',
        dashboardPowerTitle: 'قوة النظام في لوحة واحدة',
        dashboardPowerSubtitle: 'ويدجت قابلة للتخصيص، بيانات لحظية، ورؤية تنفيذية واضحة.',
        rolesTitle: 'نظام صلاحيات يضمن التحكم',
        rolesSubtitle: 'افصل مسؤوليات الإدارة والتشغيل بدقة.',
        reportsTitle: 'تقارير تساعدك تتخذ قرار أسرع',
        reportsSubtitle: 'متابعة الزيارات، الحجوزات، والمعاملات مع خيارات تصدير متعددة.',
        mobileTitle: 'تجربة جوال عملية للفريق',
        mobileSubtitle: 'تحديثات فورية للحجوزات وتنبيهات مباشرة للموظفين.',
        faqTitle: 'الأسئلة الشائعة',
        faqSubtitle: 'إجابات سريعة تساعدك قبل البدء.',
        faqItems: [
          { q: 'هل أحتاج بطاقة ائتمانية للتجربة؟', a: 'لا، يمكنك البدء بالتجربة المجانية بدون بطاقة ائتمانية.' },
          { q: 'هل يدعم النظام الفروع المتعددة؟', a: 'نعم، يمكنك إدارة أكثر من فرع من نفس الحساب.' },
          { q: 'هل يمكن تحديد صلاحيات مختلفة للموظفين؟', a: 'نعم، النظام يدعم أدوار وصلاحيات مخصصة حسب كل موظف.' },
          { q: 'هل أقدر أبيع خدمات ومنتجات واشتراكات معًا؟', a: 'نعم، يمكنك إدارة أنواع البيع المختلفة من نفس المنصة.' },
          { q: 'هل التقارير قابلة للتصدير؟', a: 'نعم، يمكنك التصدير بصيغ CSV وExcel وPDF.' },
          { q: 'هل يوجد تكامل مع Zoho وDaftra؟', a: 'نعم، التكاملات متاحة وجاهزة ضمن النظام.' },
        ],
        finalTitle: 'جاهز تنقل تشغيل نشاطك للمستوى التالي؟',
        finalSubtitle: 'ابدأ الآن وجرب كل الإمكانيات بنفسك.',
        learnAdvantages: 'تعرف على جميع المزايا',
        exploreIndustries: 'استكشف القطاعات',
      }
    : {
        brand: 'Bookati',
        heroBadge: 'Built For Saudi Businesses',
        heroTitle: 'Run your entire business from one smart platform',
        heroSubtitle:
          'A complete operating system for bookings, sales, team workflows, and customer experience.',
        ctaPrimary: 'Start Free Trial',
        ctaSecondary: 'Book Demo',
        trust: ['No credit card required', '30-day free trial', 'Cancel anytime'],
        stats: [
          { value: '40%', label: 'More bookings' },
          { value: '60%', label: 'Time saved' },
          { value: '95%', label: 'Customer satisfaction' },
          { value: '24/7', label: 'Online booking' },
        ],
        overviewTitle: 'Everything you need to know',
        overviewSubtitle: 'Clear and simple capabilities for non-technical teams.',
        overviewFeatures: [
          { key: 'dashboard', title: 'Custom Dashboard', desc: 'Drag-and-drop widgets based on your priorities.', benefit: 'See key KPIs instantly.' },
          { key: 'multilang', title: 'Multi-language system', desc: 'Arabic RTL-first UI with additional language support.', benefit: 'Easy adoption for diverse teams.' },
          { key: 'roles', title: 'Role-based permissions', desc: 'Admin, Employee, and custom role structures.', benefit: 'Precise control over access.' },
          { key: 'branches', title: 'Branch management', desc: 'Manage all branches from one platform.', benefit: 'Consistent operations across locations.' },
          { key: 'bookings', title: 'Advanced booking flow', desc: 'Create, edit, confirm, and track bookings in one flow.', benefit: 'Faster execution and better CX.' },
          { key: 'tags', title: 'Tag-based pricing', desc: 'Control slot duration and fee behavior by service context.', benefit: 'More accurate pricing logic.' },
          { key: 'analytics', title: 'Reports & analytics', desc: 'Track bookings, visitors, and transactions.', benefit: 'Decisions backed by real data.' },
          { key: 'integrations', title: 'Business integrations', desc: 'Zoho and Daftra with future-ready extension model.', benefit: 'Connected workflows, less manual effort.' },
        ],
        coreGridTitle: 'Core modules in one place',
        coreGridSubtitle: 'Each card represents a key business capability.',
        coreCards: [
          { key: 'booking', title: 'Bookings', desc: 'Admin booking management plus the public booking flow.' },
          { key: 'landing', title: 'Landing & booking link', desc: 'Public landing editor and your branded booking URL.' },
          { key: 'pos', title: 'Reception & cashier', desc: 'Reception for visits and sales; cashier checkout flows.' },
          { key: 'packages', title: 'Packages & subscribers', desc: 'Plans, renewals, and subscriber management.' },
          { key: 'offers', title: 'Offers & promotions', desc: 'Discounts and campaigns to lift conversions.' },
          { key: 'branches', title: 'Branches', desc: 'Multi-location operations from one account.' },
          { key: 'tags', title: 'Services & pricing tags', desc: 'Service catalog with tag-based duration and pricing.' },
          { key: 'employees', title: 'Staff & shifts', desc: 'Team roster and shift scheduling when enabled.' },
          { key: 'reports', title: 'Reports & exports', desc: 'Visitors, bookings, transactions, CSV/Excel/PDF.' },
          { key: 'customers', title: 'Customer portal', desc: 'Customer login, dashboard, and billing access.' },
          { key: 'roles', title: 'Roles & dashboard', desc: 'Custom permissions and drag-and-drop dashboard widgets.' },
        ],
        advantagesTitle: 'Why we are different',
        advantagesSubtitle: 'Real competitive advantages for Saudi market.',
        sellTitle: 'What you can sell',
        sellSubtitle: 'Service, product, package, subscription, and tickets.',
        industriesTitle: 'Industry-ready solutions',
        industriesSubtitle: 'Tailored use cases for each business type.',
        partnersTitle: 'Partners & Integrations',
        partnersSubtitle: 'Ready integrations now, expandable architecture for future.',
        dashboardPowerTitle: 'Operational power in one dashboard',
        dashboardPowerSubtitle: 'Drag-and-drop widgets and real-time business visibility.',
        rolesTitle: 'Role-based control',
        rolesSubtitle: 'Admin, employee, and custom role permissions.',
        reportsTitle: 'Actionable analytics',
        reportsSubtitle: 'Bookings, visitors, transactions, and exports.',
        mobileTitle: 'Mobile-first team experience',
        mobileSubtitle: 'Instant updates and notifications on the go.',
        faqTitle: 'Frequently asked questions',
        faqSubtitle: 'Quick answers before you start.',
        faqItems: [
          { q: 'Do I need a credit card to start?', a: 'No. You can start the free trial without a credit card.' },
          { q: 'Can I manage multiple branches?', a: 'Yes, multi-branch operations are supported from one account.' },
          { q: 'Can I control staff permissions?', a: 'Yes, you can configure role-based and custom permissions.' },
          { q: 'Can I sell services, products, and subscriptions together?', a: 'Yes, the platform supports multiple selling models in one flow.' },
          { q: 'Can reports be exported?', a: 'Yes, exports are available in CSV, Excel, and PDF.' },
          { q: 'Do you support Zoho and Daftra integrations?', a: 'Yes, both integrations are supported.' },
        ],
        finalTitle: 'Ready to scale your operations?',
        finalSubtitle: 'Start free and see the value yourself.',
        learnAdvantages: 'View all advantages',
        exploreIndustries: 'Explore industries',
      };
}

